### ISSUE TITLE
Borrado de usuarios, eventos y comentarios

### ISSUE THREAD

**Issue by ergl** [SaleOkase/saleokase.github.io#10]
Ahora mismo tenemos un campo `author` tanto en los comentarios como en los eventos. Dado que ambos son `foreign keys` no podemos ponerlos con referencia nula en caso de que ese usuario sea borrado.

Ahora mismo tenemos dos alternativas. O bien borramos todos los comentarios y eventos de ese usuario, o se los asignamos a un usuario `[deleted]` que comparte todo el contenido que queda cuando un usuario se borra la cuenta.

También se puede hacer mixto, no me preocupa la idea de eliminar todos sus comentarios (y con él todo el árbol de *replies*), pero en los eventos es un poco más delicado, yo esos sí que los dejaría sin tocar.

Igualmente, un usuario siempre puede borrar su contenido si lo elige, y por tanto sí que se pueden eliminar los eventos cuando lo decida.

¿Por qué opción os parece decantarnos @SaleOkase/developers ?

**Comment by Caparrini** [comment]
Para que quede constancia, (los demás hacedlo también), yo opino que si borramos el usuario que es autor de eventos y comentarios,  lo que podemos hacer es tener un campo en la base de datos que sea un deleted, y luego ocultemos los comentarios y eventos hechos por un usuario deleted, pero lo dejamos un tiempo.

**Comment by ximenaNC** [comment]
Yo estoy de acuerdo con el usuario deleted, lo he hablando con Borja es
menos caótico que borrar el usuario de golpe.

**Comment by ergl** [comment]
Finalmente seguramente nos decantemos por el marcador de deleted en el usuario, y luego a la hora de intentar pedir ese usuario, comprobar que no se encuentra eliminado.

Si lo hace, devolveremos un error que se le mostrará al usuario indicándole que el usuario ha cancelado su cuenta.

**Comment by ergl** [comment]
Reflejado en 0af8df9
